fastlane_require "securerandom"

fastlane_version "2.14.2"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "TinyAgainstTheGiants",
      workspace: "TinyAgainstTheGiants.xcworkspace",
      clean: true,
      code_coverage: true,
      skip_slack: true,
      sdk: "iphonesimulator10.2",
      devices: ["iPhone 5s", "iPhone 6s", "iPad Air 2"]
    )
  end

  desc "Creating a code signing certificate and provisioning profile"
  lane :provision do
    produce(
      app_name: "TinyAgainstTheGiants",
      language: "English",
      app_version: "1.0",
      sku: "com.vantanllc.TinyAgainstTheGiants"
      )

    cert

    sigh(force: true)
  end

  desc "Create ipa"
  lane :build do
    create_keychain(
      name: ENV["SIGNING_KEYCHAIN"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: ENV["SIGNING_KEYCHAIN_PASSWORD"],
      add_to_search_list: true
    )
    
    import_certificate(
      certificate_path: "vantan.llc.ios.distribution.p12",
      certificate_password: ENV["DISTRIBUTION_CERTIFICATE_PASSWORD"],
      keychain_name: ENV["SIGNING_KEYCHAIN"]
    )

    security set-key-partition-list -S apple-tool:,apple: -s -k ENV["SIGNING_KEYCHAIN_PASSWORD"] ENV["SIGNING_KEYCHAIN"]

    sigh(
      adhoc: false
    )

    increment_build_number

    gym(
      scheme: "TinyAgainstTheGiants",
      workspace: "TinyAgainstTheGiants.xcworkspace",
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      use_legacy_build_api: true
    )

    delete_keychain(name: ENV["SIGNING_KEYCHAIN"])
  end

  desc "Upload to App Store"
  lane :upload do
    deliver
  end

  desc "Calculate test code coverage score. Need to run test beforehand."
  lane :report_test_coverage do
    xcov(
      workspace: "TinyAgainstTheGiants.xcworkspace",
      scheme: "TinyAgainstTheGiants",
      output_directory: "xcov_output"
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
